name: test1 Build

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Unsigned APK
        run: ./gradlew assembleStandardRelease

      - name: Upload Unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: mpvplus-unsigned-apk
          path: app/build/outputs/apk/standard/release/*-unsigned.apk
